name: Build the 20.04 Docker image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/armhf

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          file: dockerfiles/focal/Dockerfile
          tags: devraymondsh/ubuntu-rust:20.04,devraymondsh/ubuntu-rust:20.04-1.86,devraymondsh/ubuntu-rust:20.04-latest,devraymondsh/ubuntu-rust:focal,devraymondsh/ubuntu-rust:focal-1.86,devraymondsh/ubuntu-rust:focal-latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
